### Idea:
* 2-phases algorithm:
   + Simple evolutive alogrithm that solves PDP
   + use local search in order to add trasnfer points 
* Hybrid evolutive algorithm that solves PDPT problem

## Instances
[Li & Lim Benchmark](https://www.sintef.no/projectweb/top/pdptw/li-lim-benchmark/)

# Hybrid evolutive algorithm

In [4]:
# Input
!cat Instance/data/lrc101.txt

In [5]:
import numpy as np
import networkx as nx

In [ ]:
class Problem:
    def __init__(self, filePath):
        TODO

In [319]:
class Nucleosome:
    def __init__(self, sol=np.array([]), key=np.array([])):
        self.sol = self.reconstruct(sol, key)
        self.key = self.randkey(key)
        self.path = np.argsort(self.sol)[(self.sol==0).sum():] + 1
    
    def reconstruct(self, sol, key):
        if sol.any():
            return sol
        pos = 1
        sol = np.array(key, copy=True)
        for i in range(len(sol)):
            if sol[i]:
                sol[i] = pos
                pos += 1
        return sol.astype(int)
            
    def randkey(self, key):
        if key.size:
            return key
        return (self.sol != 0)*4*np.exp(-self.sol)/(1 + np.exp(-self.sol))**2    


In [320]:
foo = Nucleosome(np.array([0, 1, 2, 3, 0, 4, 0]))
print(foo.sol)
Nucleosome(key=foo.key).sol
#print(foo.path)

[0 1 2 3 0 4 0]


array([0, 1, 2, 3, 0, 4, 0])

In [321]:
foos = np.array([foo, foo])
a = amap(lambda x: x.sol, foos).flatten()
len(foos.shape)

1

In [358]:
class Chromosome:
    def __init__(self, nucList=np.array([]), gen=np.array([]), problem=None):
        self.N = 2#problem.N
        if nucList.size:
            self.sol = amap(lambda x: x.sol, nucList)
            self.key = amap(lambda x: x.key, nucList)
            self.gen = self.key.flatten()
            self.path = amap(lambda x: x.path, nucList)
        else:
            self.gen = gen
            self.key = gen.reshape(self.N, int(len(gen)/self.N))
            self.sol = self.reconstruct()
            self.path = self.pathConstruction()
    
    def reconstruct(self):
        pos = 1
        sol = np.array(self.key, copy=True)
        if self.N == 1:
            for i in range(len(sol)):
                if sol[i]:
                    sol[i] = pos
                    pos += 1
        else:
            for i in range(sol.shape[0]):
                pos = 1
                for j in range(sol.shape[1]):
                    if sol[i][j]:
                        sol[i][j] = pos
                        pos += 1
        return sol.astype(int)
    
    def pathConstruction(self):
        path = list(self.sol)
        for i in range(len(path)):
            path[i] = path[i].argsort()[(path[i]==0).sum():] + 1
        return np.array(path)

In [366]:
b = Chromosome(foos)
a = Chromosome(gen=b.gen)

True

In [280]:
b.path# == b.sol

array([[2, 3, 4, 6],
       [2, 3, 4, 6]])

In [281]:
b.sol

array([[0, 1, 2, 3, 0, 4, 0],
       [0, 1, 2, 3, 0, 4, 0]])